name: Merge to fork
on:
  push:
    tags:
      - "1.*"
jobs:
  fork:
    if: github.repository_owner == 'OmegaRogue'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Merge Fork
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: main
          target_branch: pull-request-no-injection
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: pull-request
        uses: repo-sync/pull-request@v2
        if: failure()
        with:
          destination_branch: "pull-request-no-injection"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_label: "feature, automated pr"
          pr_title: "Update base repo"